### ISSUE TITLE
Please support ''file' URL scheme

### ISSUE THREAD

**Issue by dhakehurst** [equodev/equo-ide#165]
To get around issues with proxies, credentials etc,
I download some p2 repos and install locally.

old p2AsMaven supported file urls for repos.

this new p2deps does not :-(

```
Caused by: java.lang.IllegalArgumentException: Expected URL scheme 'http' or 'https' but was 'file'
	at okhttp3.HttpUrl$Builder.parse$okhttp(HttpUrl.kt:1254)
	at okhttp3.HttpUrl$Companion.get(HttpUrl.kt:1634)
	at okhttp3.Request$Builder.url(Request.kt:184)
	at dev.equo.solstice.p2.P2Client.buildRequest(P2Client.java:146)
```

**Comment by nedtwigg** [comment]
Happy to take a PR for this.

**Comment by dhakehurst** [comment]
I had a look at doing it,
but the issue seems to be in a library...so a bigger change than I can
tackle, sorry

**Comment by y1yang0** [comment]
Yes, this is useful, and I've had the urge many times to desire it to read from a file so as to avoid having to build a server proxy to just forward locally.
